#!/bin/sh

types="Host Service User HostGroup"

args=`getopt o: $*`
if test $? -ne 0
then
	echo "usage: lookupgen.sh [-o file]"
	exit 2
fi
set -- $args
while test "$#" -ne 0
do
	case "$1"
	in
		-o)
			file="$2"; shift; shift;;
		--)
			shift; break;;
	esac
done

head="// Code generated by $0 $@; DO NOT EDIT.

package icinga

import \"fmt\"
"

if test -n "$file"
then
	echo "$head" > "$file"
else
	echo "$head"
fi

for t in $types
do
	if test -n "$file"
	then
		awk -v "type=$t" -f crud.awk crud.skel >> "$file"
	else
		awk -v "type=$t" -f crud.awk crud.skel
	fi
done
